package api

import (
	"fmt"

	recurly "github.com/blacklightcms/go-recurly"
)

var _ recurly.BillingService = &BillingService{}

// BillingService handles all interaction with the billing info portion
// of the recurly API.
type BillingService struct {
	client *recurly.Client
}

// Get returns only the account's current billing information.
// https://docs.recurly.com/api/billing-info#lookup-billing-info
func (s *BillingService) Get(accountCode string) (*recurly.Response, *recurly.Billing, error) {
	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("GET", action, nil, nil)
	if err != nil {
		return nil, nil, err
	}

	var dst recurly.Billing
	resp, err := s.client.Do(req, &dst)

	return resp, &dst, err
}

// Create creates the account's billing information with credit card or
// bank account info. It is recommended you use recurly.js and a token with the CreateWithToken
// method instead.
// https://dev.recurly.com/docs/create-an-accounts-billing-info-credit-card
// https://dev.recurly.com/docs/create-an-accounts-billing-info-bank-account
func (s *BillingService) Create(accountCode string, b recurly.Billing) (*recurly.Response, *recurly.Billing, error) {
	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("POST", action, nil, b)
	if err != nil {
		return nil, nil, err
	}

	var dst recurly.Billing
	resp, err := s.client.Do(req, &dst)

	return resp, &dst, err
}

// CreateWithToken creates an account's billing information using a token
// generated by Recurly.js. Returns the account's created Billing Information.
// https://docs.recurly.com/api/billing-info#create-billing-info-token
func (s *BillingService) CreateWithToken(accountCode string, token string) (*recurly.Response, *recurly.Billing, error) {
	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("POST", action, nil, recurly.Billing{Token: token})
	if err != nil {
		return nil, nil, err
	}

	var dst recurly.Billing
	resp, err := s.client.Do(req, &dst)

	return resp, &dst, err
}

// Update updates the account's billing information with credit card or
// bank info.It is recommended you use recurly.js and a token with the
// UpdateWithToken method instead.
// https://dev.recurly.com/docs/update-an-accounts-billing-info-credit-card
// https://dev.recurly.com/docs/update-an-accounts-billing-info-bank-account
func (s *BillingService) Update(accountCode string, b recurly.Billing) (*recurly.Response, *recurly.Billing, error) {
	// Create clean billing object with write-only fields to avoid errors
	// like sending additional/unknown/read-only fields.
	clean := recurly.Billing{
		FirstName:         b.FirstName,
		LastName:          b.LastName,
		Address:           b.Address,
		Address2:          b.Address2,
		City:              b.City,
		State:             b.State,
		Zip:               b.Zip,
		Country:           b.Country,
		Phone:             b.Phone,
		VATNumber:         b.VATNumber,
		IPAddress:         b.IPAddress,
		Number:            b.Number,
		Month:             b.Month,
		Year:              b.Year,
		VerificationValue: b.VerificationValue,
		NameOnAccount:     b.NameOnAccount,
		RoutingNumber:     b.RoutingNumber,
		AccountNumber:     b.AccountNumber,
		AccountType:       b.AccountType,
	}

	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("PUT", action, nil, clean)
	if err != nil {
		return nil, nil, err
	}

	var dst recurly.Billing
	resp, err := s.client.Do(req, &dst)

	return resp, &dst, err
}

// UpdateWithToken updates an account's billing information using a token
// generated by Recurly.js. Returns the account's created Billing Information.
// https://docs.recurly.com/api/billing-info#update-billing-info-token
func (s *BillingService) UpdateWithToken(accountCode string, token string) (*recurly.Response, *recurly.Billing, error) {
	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("PUT", action, nil, recurly.Billing{Token: token})
	if err != nil {
		return nil, nil, err
	}

	var dst recurly.Billing
	resp, err := s.client.Do(req, &dst)

	return resp, &dst, err
}

// Clear removes any stored billing information for an account. If the account
// has a subscription, the renewal will go into past due unless you update the
// billing info before the renewal occurs.
// https://docs.recurly.com/api/billing-info#clear-billing-info
func (s *BillingService) Clear(accountCode string) (*recurly.Response, error) {
	action := fmt.Sprintf("accounts/%s/billing_info", accountCode)
	req, err := s.client.NewRequest("DELETE", action, nil, nil)
	if err != nil {
		return nil, err
	}

	return s.client.Do(req, nil)
}
